Fixed ttl for soa reacord to minimum of ttl and minimum field
dnsjava/dnsjava pull request #191
Opened 2021-04-18 07:15 UTC by amitknx

I have been seeing an error where in case of negative answer(NXDOMAIN), ttl of cache is being set at MINIMUM field of the SOA record (see [issue#186](https://github.com/dnsjava/dnsjava/issues/186)) whereas [RFC2308](https://tools.ietf.org/html/rfc2308), Section 3 says:

> The TTL of this record is set from the minimum of the MINIMUM field of the SOA record and the TTL of the SOA itself, and indicates how long a resolver may cache the negative answer.

I have explore the code and found out that it indeed is being set for MINIMUM field, I have added a fix for it to set the cache ttl at minimum of the MINIMUM field of the SOA record and the TTL of the SOA.

2021-04-18 10:42 UTC, ibauersachs commented
Yes, you're right. I only looked at `org.xbill.DNS.Cache#addNegative`, which needs the same `Math.min()` call. Would you mind updating the PR so that the minimum is considered in both checks?

2021-04-18 10:43 UTC, ibauersachs requested changes
Yes, you're right. I only looked at org.`xbill.DNS.Cache#addNegative`, which needs the same `Math.min()` call. Would you mind updating the PR so that the minimum is considered in both checks?

2021-04-18 12:42 UTC, amitknx commented
Sorry, my mistake.. updated the PR

2021-04-18 13:31 UTC, merged

2021-04-18 13:32 UTC, ibauersachs commented
Thanks!

2021-05-24 08:04 UTC, amitknx commented
@ibauersachs : Hi, When can I expect this to be released in 3.4? Is there a timeline?

2021-05-24 08:54 UTC, ibauersachs commented
@amitknx I was hoping to get reviews for two open PRs from @nresare. I'll wait another week or two and would release anyway then.

2021-05-24 09:49 UTC, amitknx commented
ok thanks for the info.