support custom hosts file size
dnsjava/dnsjava pull request #349
Opened 2024-10-28 07:01 UTC by flaming-archer

Sometimes our/etc/hosts file is very large, and the machine's memory is large enough to load it into memory. At this point, we can customize this parameter.

2024-11-10 01:30 UTC, ibauersachs commented
It's fine to add this option. Please:
- add tests for it
- document the new option in the readme

2024-11-15 01:34 UTC, flaming-archer commented
@ibauersachs pls take look at it.

2024-11-25 13:23 UTC, ibauersachs requested changes

2024-11-25 13:23 UTC, ibauersachs commented on README.adoc
> +3+|Set the size of the hosts file to be loaded at a time，in bytes.
Use a normal comma please.

2024-11-25 13:23 UTC, ibauersachs commented on src/test/java/org/xbill/DNS/hosts/HostsFileParserTest.java
> +    System.clearProperty("dnsjava.hostsfile.max_size");
If the assert fails, the property is never unset. Please wrap this all in a try/finally construct, like in this test case:

https://github.com/dnsjava/dnsjava/blob/a6371af00867d13e5b3dbee040f640e93420fb21/src/test/java/org/xbill/DNS/NioTcpClientTest.java#L42-L47

2024-11-25 13:23 UTC, ibauersachs commented on README.adoc
> +.2+|dnsjava.hostsfile.max_size
Please name the property `dnsjava.hostsfile.max_size_bytes`, otherwise this might be confused with the number of lines to read.

2024-11-25 15:27 UTC, flaming-archer commented
@ibauersachs pls review again, changed already.

2024-11-25 16:10 UTC, ibauersachs commented on README.adoc
> +.2+|dnsjava.hostsfile.max_size
The property name is changed now, but not the doc.

2024-11-25 16:11 UTC, ibauersachs commented on src/test/java/org/xbill/DNS/hosts/HostsFileParserTest.java
> +    HostsFileParser hostsFileParser = generateLargeHostsFile("testBigFileCompletelyCachedA");
Please move this line also into the try

2024-11-25 16:26 UTC, ibauersachs commented on README.adoc
> +3+|Set the size of the hosts file to be loaded at a time,in bytes.
`time, in`

2024-11-25 18:06 UTC, merged